export default function decorate(block) {
  // Deconstruct the first two divs inside the generated by AEM block
  const [userImg, userName] = block.children;
  // Assigning class to use for styling
  userImg.className = 'userIndicator__img';
  userName.className = 'userIndicator__name';
  userImg.querySelector('div').classList.add('userIndicator__picture');
  userName.querySelector('div').classList.add('userIndicator__username');
  // Create a custom elements
  const indicator = document.createElement('div');
  indicator.className = 'userIndicator__indicator';
  const indicatorInner = document.createElement('div');
  indicatorInner.className = 'userIndicator__indicator-inner';
  // Added to the parent element
  indicatorInner.append(indicator);
  userImg.append(indicatorInner);
}
