function decorate(block: Element) {
  // Deconstruct the first two divs inside the generated by AEM block
  const [userImg, userName] = block.children
  const el = document.querySelectorAll('.userindicator')
  // Logout state
  el[1].classList.add('userindicator--is-not-loggedin')

  // Assigning class to use for styling
  userImg.className = 'user-indicator-img'
  userName.className = 'user-indicator-name'
  userImg.querySelector('div')?.classList.add('user-indicator-picture')
  userName.querySelector('div')?.classList.add('user-indicator-username')
  // Create a custom elements
  const indicator = document.createElement('div')
  indicator.className = 'user-indicator-indicator'
  const indicatorInner = document.createElement('div')
  indicatorInner.className = 'user-indicator-indicator-inner'
  // Added to the parent element
  indicatorInner.append(indicator)
  userImg.append(indicatorInner)
}

export default decorate
